# 二维码扫描器的COM口
# 妇科机器使用的是COM5
SERIAL_PORT = "COM8"
# 波特率
BAUDRATE = "115200"

# PostgreSQL数据库配置
POSTGRES_HOST = "192.168.88.41"
POSTGRES_PORT = 5432
POSTGRES_USERNAME = "lyra_ops"
POSTGRES_PASSWORD = "pVc7EPshyba5"  # 请替换为实际密码
POSTGRES_DATABASE = "lyradb"
